<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Decomposing the variance of the specification curve • specr</title>
<!-- jquery --><script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script><!-- Bootstrap --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha256-916EbMg70RQy9LHiGkXzG8hSg9EdNy97GazNG/aiY1w=" crossorigin="anonymous">
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha256-U5ZEeKfGNOja007MMD3YBI0A3OSZOQbeG6z2f2Y0hu8=" crossorigin="anonymous"></script><!-- Font Awesome icons --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.7.1/css/all.min.css" integrity="sha256-nAmazAk6vS34Xqo0BSrTb+abbtFlgsFK7NKSi6o7Y78=" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.7.1/css/v4-shims.min.css" integrity="sha256-6qHlizsOWFskGlwVOKuns+D1nB6ssZrHQrNj1wGplHc=" crossorigin="anonymous">
<!-- clipboard.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.4/clipboard.min.js" integrity="sha256-FiZwavyI2V6+EXO1U+xzLG3IKldpiTFf3153ea9zikQ=" crossorigin="anonymous"></script><!-- headroom.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.9.4/headroom.min.js" integrity="sha256-DJFC1kqIhelURkuza0AvYal5RxMtpzLjFhsnVIeuk+U=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.9.4/jQuery.headroom.min.js" integrity="sha256-ZX/yNShbjqsohH1k95liqY9Gd8uOiE1S4vZc+9KQ1K4=" crossorigin="anonymous"></script><!-- pkgdown --><link href="../pkgdown.css" rel="stylesheet">
<script src="../pkgdown.js"></script><meta property="og:title" content="Decomposing the variance of the specification curve">
<meta property="og:description" content="">
<meta name="twitter:card" content="summary">
<!-- mathjax --><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js" integrity="sha256-nvJJv9wWKEm88qvoQl9ekL2J+k/RWIsaSScxxlsrv8k=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/config/TeX-AMS-MML_HTMLorMML.js" integrity="sha256-84DKXVJXs0/F8OTMzX4UR909+jtl4G7SPypPavF+GfA=" crossorigin="anonymous"></script><!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>
<body>
    <div class="container template-article">
      <header><div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">
        <a class="navbar-link" href="../index.html">specr</a>
        <span class="version label label-default" data-toggle="tooltip" data-placement="bottom" title="Released version">0.1.1</span>
      </span>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
<li>
  <a href="../index.html">
    <span class="fas fa fas fa-home fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="../articles/specr.html">Get started</a>
</li>
<li>
  <a href="../reference/index.html">Reference</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Articles
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
<li>
      <a href="../articles/custom-plot.html">Customizing plots</a>
    </li>
    <li>
      <a href="../articles/decompose_var.html">Decomposing the variance of the specification curve</a>
    </li>
    <li>
      <a href="../articles/invest-spec.html">Investigating specific specifications</a>
    </li>
    <li>
      <a href="../articles/progress.html">Visualizing progress</a>
    </li>
  </ul>
</li>
      </ul>
<ul class="nav navbar-nav navbar-right"></ul>
</div>
<!--/.nav-collapse -->
  </div>
<!--/.container -->
</div>
<!--/.navbar -->

      

      </header><div class="row">
  <div class="col-md-9 contents">
    <div class="page-header toc-ignore">
      <h1>Decomposing the variance of the specification curve</h1>
            
      
      
      <div class="hidden name"><code>decompose_var.rmd</code></div>

    </div>

    
    
<p>This vignette exemplifies ways to decompose and identify variance components in any statistic obtained by running a specification curve analysis.</p>
<div id="run-the-specification-curve-analysis" class="section level2">
<h2 class="hasAnchor">
<a href="#run-the-specification-curve-analysis" class="anchor"></a>1. Run the specification curve analysis</h2>
<p>In order to have some data to work with, we run the minimal example contained in the package.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1"></a><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span>(specr)</span>
<span id="cb1-2"><a href="#cb1-2"></a><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span>(ggplot2)</span>
<span id="cb1-3"><a href="#cb1-3"></a><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span>(dplyr)</span>
<span id="cb1-4"><a href="#cb1-4"></a></span>
<span id="cb1-5"><a href="#cb1-5"></a><span class="co"># run spec analysis</span></span>
<span id="cb1-6"><a href="#cb1-6"></a>results &lt;-<span class="st"> </span><span class="kw"><a href="../reference/run_specs.html">run_specs</a></span>(example_data,</span>
<span id="cb1-7"><a href="#cb1-7"></a>                     <span class="dt">y =</span> <span class="kw"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="st">"y1"</span>, <span class="st">"y2"</span>),</span>
<span id="cb1-8"><a href="#cb1-8"></a>                     <span class="dt">x =</span> <span class="kw"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="st">"x1"</span>, <span class="st">"x2"</span>),</span>
<span id="cb1-9"><a href="#cb1-9"></a>                     <span class="dt">model =</span> <span class="st">"lm"</span>,</span>
<span id="cb1-10"><a href="#cb1-10"></a>                     <span class="dt">controls =</span> <span class="kw"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="st">"c1"</span>, <span class="st">"c2"</span>),</span>
<span id="cb1-11"><a href="#cb1-11"></a>                     <span class="dt">subset =</span> <span class="kw"><a href="https://rdrr.io/r/base/list.html">list</a></span>(<span class="dt">group1 =</span> <span class="kw"><a href="https://rdrr.io/r/base/unique.html">unique</a></span>(example_data<span class="op">$</span>group1),</span>
<span id="cb1-12"><a href="#cb1-12"></a>                                   <span class="dt">group2 =</span> <span class="kw"><a href="https://rdrr.io/r/base/unique.html">unique</a></span>(example_data<span class="op">$</span>group2)))</span></code></pre></div>
<p>Let’s quickly get some ideas about the specification curve by using <code><a href="../reference/summarise_specs.html">summarise_specs()</a></code></p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1"></a><span class="co"># Overall median</span></span>
<span id="cb2-2"><a href="#cb2-2"></a><span class="kw"><a href="../reference/summarise_specs.html">summarise_specs</a></span>(results)</span></code></pre></div>
<pre><code>## # A tibble: 1 x 7
##   median   mad   min   max   q25   q75   obs
##    &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1   3.59  4.56 -2.05  9.58  1.03  7.63   123</code></pre>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1"></a><span class="co"># By choices</span></span>
<span id="cb4-2"><a href="#cb4-2"></a><span class="kw"><a href="../reference/summarise_specs.html">summarise_specs</a></span>(results,     </span>
<span id="cb4-3"><a href="#cb4-3"></a>                y, controls)</span></code></pre></div>
<pre><code>## # A tibble: 8 x 9
## # Groups:   y [2]
##   y     controls      median   mad   min   max   q25   q75   obs
##   &lt;chr&gt; &lt;chr&gt;          &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1 y1    c1             7.72  0.744  3.53  8.96 6.44   8.13   123
## 2 y1    c1 + c2        7.03  1.39   3.49  8.71 6.25   8.05   123
## 3 y1    c2             7.15  1.44   3.94  9.58 6.35   8.37   123
## 4 y1    no covariates  7.97  1.40   4.24  9.28 6.80   8.42   123
## 5 y2    c1             1.11  1.40  -2.05  2.79 0.144  1.83   123
## 6 y2    c1 + c2        0.796 1.11  -1.94  2.83 0.101  1.37   123
## 7 y2    c2             0.690 1.00  -1.61  3.64 0.367  1.82   123
## 8 y2    no covariates  1.31  0.931 -1.80  3.67 0.674  1.92   123</code></pre>
<p>We see that it makes quite a difference whether <code>y1</code> or <code>y2</code> is used as independent variable.</p>
</div>
<div id="estimate-a-simple-multilevel-model" class="section level2">
<h2 class="hasAnchor">
<a href="#estimate-a-simple-multilevel-model" class="anchor"></a>2. Estimate a simple multilevel model</h2>
<p>We can think of the specification curve analysis as a factorial design in which we investigate the influence of different types of analytical choices on a resulting coefficient or test statistic. One way to investigate these effects is to ask how much variance in the specification curve is explained by what (or which combination of) analytical choices.</p>
<p>In a first step, we therefore have to estimate a simple multilevel model without predictors, yet with specific random effects that represent the analytical choices.</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1"></a><span class="co"># Package to estimate multilevel models</span></span>
<span id="cb6-2"><a href="#cb6-2"></a><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span>(lme4)</span>
<span id="cb6-3"><a href="#cb6-3"></a></span>
<span id="cb6-4"><a href="#cb6-4"></a><span class="co"># Estimate model</span></span>
<span id="cb6-5"><a href="#cb6-5"></a>m1 &lt;-<span class="st"> </span><span class="kw"><a href="https://rdrr.io/pkg/lme4/man/lmer.html">lmer</a></span>(estimate <span class="op">~</span><span class="st"> </span><span class="dv">1</span> <span class="op">+</span><span class="st"> </span>(<span class="dv">1</span><span class="op">|</span>x) <span class="op">+</span><span class="st"> </span>(<span class="dv">1</span><span class="op">|</span>y) <span class="op">+</span><span class="st"> </span>(<span class="dv">1</span><span class="op">|</span>controls) <span class="op">+</span><span class="st"> </span>(<span class="dv">1</span><span class="op">|</span>subsets), <span class="dt">data =</span> results)</span>
<span id="cb6-6"><a href="#cb6-6"></a></span>
<span id="cb6-7"><a href="#cb6-7"></a><span class="co"># Check model summary</span></span>
<span id="cb6-8"><a href="#cb6-8"></a><span class="kw"><a href="https://rdrr.io/r/base/summary.html">summary</a></span>(m1)</span></code></pre></div>
<pre><code>## Linear mixed model fit by REML ['lmerMod']
## Formula: estimate ~ 1 + (1 | x) + (1 | y) + (1 | controls) + (1 | subsets)
##    Data: results
## 
## REML criterion at convergence: 591.7
## 
## Scaled residuals: 
##      Min       1Q   Median       3Q      Max 
## -2.85509 -0.60698 -0.03593  0.55041  2.83207 
## 
## Random effects:
##  Groups   Name        Variance Std.Dev.
##  subsets  (Intercept)  0.76138 0.8726  
##  controls (Intercept)  0.03861 0.1965  
##  y        (Intercept) 19.72906 4.4417  
##  x        (Intercept)  0.42335 0.6507  
##  Residual              1.00930 1.0046  
## Number of obs: 192, groups:  subsets, 12; controls, 4; y, 2; x, 2
## 
## Fixed effects:
##             Estimate Std. Error t value
## (Intercept)    4.079      3.187    1.28</code></pre>
<p>We have now stored the random effects in the object <code>m</code>. We can already see that most variance is related to the random effect <code>y|intercept</code>. Yet, how much exactly?</p>
</div>
<div id="estimate-intraclass-correlations" class="section level2">
<h2 class="hasAnchor">
<a href="#estimate-intraclass-correlations" class="anchor"></a>3. Estimate intraclass correlations</h2>
<p>Specr offers to ways to decompose the variance of the specification curve. First, we can simply compute the intraclass correlations using the function <code><a href="../reference/icc_specs.html">icc_specs()</a></code>.</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1"></a><span class="kw"><a href="../reference/icc_specs.html">icc_specs</a></span>(m1) <span class="op">%&gt;%</span></span>
<span id="cb8-2"><a href="#cb8-2"></a><span class="st">  </span><span class="kw"><a href="https://dplyr.tidyverse.org/reference/mutate_all.html">mutate_if</a></span>(is.numeric, round, <span class="dv">2</span>)</span></code></pre></div>
<pre><code>##        grp  vcov  icc percent
## 1  subsets  0.76 0.03    3.47
## 2 controls  0.04 0.00    0.18
## 3        y 19.73 0.90   89.83
## 4        x  0.42 0.02    1.93
## 5 Residual  1.01 0.05    4.60</code></pre>
<p>We can see that 89.83% of the variance in the obtained results is related to choosing different dependent variables. Only small parts of the variance are explained by other analytical choices.</p>
</div>
<div id="plot-variance-components" class="section level2">
<h2 class="hasAnchor">
<a href="#plot-variance-components" class="anchor"></a>4. Plot variance components</h2>
<p>Second, we can alternatively use the function <code><a href="../reference/plot_variance.html">plot_variance()</a></code> to obtain a visualization. The function calls <code><a href="../reference/icc_specs.html">icc_specs()</a></code> automatically. We can hence pass the multilevel results object directly. Further customizations via the ggplot2-syntax is possible.</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1"></a><span class="kw"><a href="../reference/plot_variance.html">plot_variance</a></span>(m1) <span class="op">+</span></span>
<span id="cb10-2"><a href="#cb10-2"></a><span class="st">  </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/lims.html">ylim</a></span>(<span class="dv">0</span>, <span class="dv">100</span>)</span></code></pre></div>
<p><img src="decompose_var_files/figure-html/unnamed-chunk-5-1.png" width="700"></p>
</div>
<div id="further-investigating-variance-components" class="section level2">
<h2 class="hasAnchor">
<a href="#further-investigating-variance-components" class="anchor"></a>5. Further investigating variance components</h2>
<p>You might ask yourself why we did not include the multilevel model estimation in the <code><a href="../reference/icc_specs.html">icc_specs()</a></code> function. The reason is straight-forward: In many cases, it might be of interest to decompose the variance in different ways (e.g., including interactions between the analytical choices). In this case, we only need to specify the respective multilevel model (with alternative random effects) and we can again obtain a result table of a plot.</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1"></a>m2 &lt;-<span class="st"> </span><span class="kw"><a href="https://rdrr.io/pkg/lme4/man/lmer.html">lmer</a></span>(estimate <span class="op">~</span><span class="st"> </span><span class="dv">1</span> <span class="op">+</span><span class="st"> </span>(<span class="dv">1</span><span class="op">|</span>x) <span class="op">+</span><span class="st"> </span>(<span class="dv">1</span><span class="op">|</span>y) <span class="op">+</span><span class="st"> </span>(<span class="dv">1</span><span class="op">|</span>controls) <span class="op">+</span><span class="st"> </span>(<span class="dv">1</span><span class="op">|</span>subsets) <span class="op">+</span><span class="st"> </span>(<span class="dv">1</span><span class="op">|</span>x<span class="op">:</span>y) <span class="op">+</span><span class="st"> </span>(<span class="dv">1</span><span class="op">|</span>y<span class="op">:</span>controls) <span class="op">+</span><span class="st"> </span>(<span class="dv">1</span><span class="op">|</span>y<span class="op">:</span>subsets), <span class="dt">data =</span> results)</span>
<span id="cb11-2"><a href="#cb11-2"></a></span>
<span id="cb11-3"><a href="#cb11-3"></a><span class="co"># Get table</span></span>
<span id="cb11-4"><a href="#cb11-4"></a><span class="kw"><a href="../reference/icc_specs.html">icc_specs</a></span>(m2) <span class="op">%&gt;%</span></span>
<span id="cb11-5"><a href="#cb11-5"></a><span class="st">  </span><span class="kw"><a href="https://dplyr.tidyverse.org/reference/mutate_all.html">mutate_if</a></span>(is.numeric, round, <span class="dv">2</span>)</span></code></pre></div>
<pre><code>##          grp  vcov  icc percent
## 1  y:subsets  0.76 0.03    3.49
## 2    subsets  0.41 0.02    1.87
## 3 y:controls  0.00 0.00    0.00
## 4        x:y  0.02 0.00    0.09
## 5   controls  0.05 0.00    0.22
## 6          y 19.46 0.90   89.55
## 7          x  0.42 0.02    1.92
## 8   Residual  0.62 0.03    2.87</code></pre>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1"></a><span class="co"># Plot results</span></span>
<span id="cb13-2"><a href="#cb13-2"></a><span class="kw"><a href="../reference/plot_variance.html">plot_variance</a></span>(m2)</span></code></pre></div>
<p><img src="decompose_var_files/figure-html/unnamed-chunk-6-1.png" width="700"></p>
<p>We can see that the interaction between analytical choices relating to subsets and dependent variables explains 3.49%.</p>
</div>
<div id="investigating-other-statistics" class="section level2">
<h2 class="hasAnchor">
<a href="#investigating-other-statistics" class="anchor"></a>6. Investigating other statistics</h2>
<p>Finally it should be noted that other obtained statistics can be investigated as well (not only the main estimate, e.g., a regression coefficient).</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1"></a>m3 &lt;-<span class="st"> </span><span class="kw"><a href="https://rdrr.io/pkg/lme4/man/lmer.html">lmer</a></span>(p.value <span class="op">~</span><span class="st"> </span><span class="dv">1</span> <span class="op">+</span><span class="st"> </span>(<span class="dv">1</span><span class="op">|</span>x) <span class="op">+</span><span class="st"> </span>(<span class="dv">1</span><span class="op">|</span>y) <span class="op">+</span><span class="st"> </span>(<span class="dv">1</span><span class="op">|</span>controls) <span class="op">+</span><span class="st"> </span>(<span class="dv">1</span><span class="op">|</span>subsets), <span class="dt">data =</span> results)</span></code></pre></div>
<pre><code>## boundary (singular) fit: see ?isSingular</code></pre>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1"></a><span class="kw"><a href="../reference/icc_specs.html">icc_specs</a></span>(m3) <span class="op">%&gt;%</span></span>
<span id="cb16-2"><a href="#cb16-2"></a><span class="st">  </span><span class="kw"><a href="https://dplyr.tidyverse.org/reference/mutate_all.html">mutate_if</a></span>(is.numeric, round, <span class="dv">2</span>)</span></code></pre></div>
<pre><code>##        grp vcov  icc percent
## 1  subsets 0.00 0.04    4.07
## 2 controls 0.00 0.00    0.00
## 3        y 0.02 0.30   29.99
## 4        x 0.00 0.01    0.74
## 5 Residual 0.03 0.65   65.21</code></pre>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1"></a><span class="kw"><a href="../reference/plot_variance.html">plot_variance</a></span>(m3)</span></code></pre></div>
<p><img src="decompose_var_files/figure-html/unnamed-chunk-7-1.png" width="700"></p>
</div>
  </div>

  <div class="col-md-3 hidden-xs hidden-sm" id="sidebar">

        <div id="tocnav">
      <h2 class="hasAnchor">
<a href="#tocnav" class="anchor"></a>Contents</h2>
      <ul class="nav nav-pills nav-stacked">
<li><a href="#run-the-specification-curve-analysis">1. Run the specification curve analysis</a></li>
      <li><a href="#estimate-a-simple-multilevel-model">2. Estimate a simple multilevel model</a></li>
      <li><a href="#estimate-intraclass-correlations">3. Estimate intraclass correlations</a></li>
      <li><a href="#plot-variance-components">4. Plot variance components</a></li>
      <li><a href="#further-investigating-variance-components">5. Further investigating variance components</a></li>
      <li><a href="#investigating-other-statistics">6. Investigating other statistics</a></li>
      </ul>
</div>
      </div>

</div>



      <footer><div class="copyright">
  <p>Developed by Philipp K. Masur, Michael Scharkow.</p>
</div>

<div class="pkgdown">
  <p>Site built with <a href="https://pkgdown.r-lib.org/">pkgdown</a> 1.4.1.</p>
</div>

      </footer>
</div>

  


  </body>
</html>
